### model
model_name_or_path: google/gemma-3-1b-it
quantization_bit: 4

### method
finetuning_type: lora
lora_rank: 2
lora_alpha: 4
lora_target: q_proj,v_proj

### dataset
dataset: anchor-assistant
template: gemma
cutoff_len: 512
max_samples: 500

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 16
learning_rate: 1.0e-4
num_train_epochs: 2
fp16: true

### output
output_dir: saves/gemma-lora
